config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  get    '/new_article',   to: 'articles#new'
  get    '/new_category',  to: 'categories#new'
  get    '/signup',        to: 'users#new'
  get    '/signup',        to: 'users#create'
  get    '/login',         to: 'sessions#new'
  post   '/login',         to: 'sessions#create'
  delete '/logout',        to: 'sessions#destroy'

  resources :users, only: [:new, :create]
  resources :categories, only: [:new, :show, :create, :destroy]
  resources :articles, only: [:new, :create] do
    resources :votes, only: [:create, :destroy]

  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true, length: { maximum: 50,
                                              too_long: '50 characters in Article title is the maximum allowed.',
                                              minimum: 4 }
  validates :text, presence: true, length: { maximum: 1000,
                                             too_long: '1000 characters in Article content is the maximum allowed.',
                                             minimum: 100 }
  validates :category_id, presence: true
  scope :ordered_most_recent, -> { order(created_at: :desc) }

  belongs_to :user
  belongs_to :category
  has_many :votes, dependent: :destroy

  VALID_IMAGE = /.(?:jpg|png)/i.freeze
  validates :image, presence: true, length: { maximum: 255 },
                    format: { with: VALID_IMAGE }
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true, length: { maximum: 20 }
  validates :priority, presence: true, inclusion: 1..5
  has_many :articles
  scope :ordered_by_priority, -> { order(priority: :asc) }
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, length: { maximum: 20 }, uniqueness: { case_sensitive: false }
  has_many :articles
  has_many :votes, dependent: :destroy
end

app/models/vote.rb
class Vote < ApplicationRecord
  validates :user_id, uniqueness: { scope: :article_id }

  belongs_to :user
  belongs_to :article
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionHelper
  include VoteHelper
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :require_logged_in

  def new
    @article = Article.new
    @categories = Category.all
  end

  def create
    @categories = Category.all
    @user = current_user
    @article = @user.articles.new(post_params)

    if @article.save
      redirect_to root_path
      flash[:success] = 'Article created Succesfully'
    else
      render 'new'
    end
  end

  private

  def post_params
    params.require(:article).permit(:text, :title, :category_id, :image)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def new
    @category = Category.new
  end

  def show
    @category = Category.find(params[:id])
    @articles = @category.include(:id).articles.ordered_most_recent
  end

  def create
    @category = Category.new(category_params)
    if @category.save

      redirect_to new_article_path
      flash[:success] = 'Category created succesfully '
    else
      render 'new'
    end
  end

  private

  def category_params
    params.require(:category).permit(:name, :priority)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :require_logged_in
  def index
    @categories = Category.all
    @most_voted_article = most_voted_article
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    user = User.find_by(name: params[:session][:name])
    if user
      log_in user
      redirect_to root_path
      flash[:info] = 'Logged in correctly'
    else
      flash.now[:danger] = 'This user does not exist'
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      redirect_to root_path
      flash[:success] = 'Signup Succesfull'
    else
      render 'new'
    end
  end

  private

  def user_params
    params.require(:user).permit(:name)
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  def create
    @vote = current_user.votes.new(article_id: params[:article_id])
    @category = Article.find_by(id: params[:article_id]).category
    if @vote.save
      redirect_to category_path(@category) and flash.now[:info] = 'You vote this article'

    else
      flash[:info] = 'You cannot vote for this article.'
    end
  end

  def destroy
    @category = Article.find_by(id: params[:article_id]).category
    vote = Vote.find_by(id: params[:id], user: current_user, article_id: params[:article_id])
    if vote
      vote.destroy
      redirect_to category_path(@category) and flash.now[:info] = 'You unvote for this article'

    else
      flash[:info] = 'You cannot unvote an article did not vote before.'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/session_helper.rb
module SessionHelper
  def log_out
	flash[:success] = 'Signout Succesfull'
	session.delete(:user_id)
	@current_user = nil	
  end

  def log_in(user)
	session[:user_id] = user.id	
 end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !current_user.nil?
  end

  def require_logged_in
    return if logged_in?

    flash[:danger] = 'You must loggin first'
    redirect_to login_path
  end
end

app/helpers/vote_helper.rb
module VoteHelper
  def most_voted_article
    articles = Article.all
    best_count = 0
    best_article = Article.all.first
    articles.each do |article|
      if article.votes.size > best_count
        best_article = article
        best_count = article.votes.size
      end
    end
    best_article
  end

  def vote_or_unvote(article, style = 'label-form')
    if logged_in?
      vote = Vote.find_by(article: article, user: current_user)

      if vote
        link_to (fa_icon 'thumbs-o-down'), article_vote_path(id: vote.id, article_id: article.id),
                class: style, method: :delete
      else
        link_to (fa_icon 'thumbs-o-up '), article_votes_path(article_id: article.id), class: style, method: :post
      end

    else
      link_to('Must be logged in to vote', login_path)
    end
  end
end

app/views/articles/index.html.erb
<div class="container-fluid">

  <div class="row">
    <%  @articles.each do |article| %>
    <div class="col-4">
      <h1><%= article.title %></h1>
      <p><%= article.text %>  </p>
      <strong><%= article.category.name %>  </strong>

      <span>Number of votes  <%= article.votes.size %></span>
      <%= vote_or_unvote(article) %>
      <span class='post-date'> <%= article.created_at.strftime("%Y/%m/%d") %> </span>
      <hr>
    </div>
    <% end %>

  </div>
</div>

app/views/articles/new.html.erb
<div class=" col-12 bg-brown p-5">
  <h1 class="page-title-wihte ">Write an article</h1>
</div>

<div class="container">


  <%= form_for(@article) do |form| %>
  <%= form.label :title, "Title", class: "label-form mt-4" %>
  <%= form.text_field :title, class: 'form-control', placeholder: 'Add Title' %>

  <%= form.label :image, "Image ", class: "label-form mt-4" %>
  <%= form.text_field :image, class: 'form-control mb-4', placeholder: 'ej: https://i.imgur.com/8R0jcdO.jpg ' %>

<%= form.label :category, "Category ", class: "label-form mt-4" %> <br>
  <%= form.collection_select :category_id, @categories, :id, :name, {prompt: "Select Category"}, {class: 'mdb-select md-form' } %>
  <%= link_to('Create new Category', new_category_path, class: 'label-form') %>
<br>
  <%= form.label "Content", class: "label-form mt-4" %>
  <%= form.text_area :text, class: 'form-control', placeholder: 'Add Content...', size: "60x12" %>

  <% if @article.errors.full_messages.any? %>
  <div class="alert alert-danger" role="alert">
    <%= "Post could not be saved. #{@article.errors.full_messages.join('. ')}" %>
  </div>
  <% end %>

  <%= form.submit 'Create Article', class: 'btn send-button mt-4 mb-5' %>
  <% end %>


</div>

app/views/categories/new.html.erb
<div class=" col-12 bg-brown p-5">
  <h1 class="page-title-wihte">New category </h1>
</div>
<div class="container mt-5  h-75">
  <% if @category.errors.full_messages.any? %>
  <div class="alert alert-danger" role="alert">
    <%= "Post could not be saved. #{@category.errors.full_messages.join('. ')}" %>
  </div>
  <% end %>
  <%= form_for(@category) do |f| %> <%= render 'shared/error_messages' %>
  <%= f.label :name, "Name of category", class: "label-form mt-4" %>
  <%= f.text_field :name, class: 'form-control' %>
  <%= f.label :priority, "Priority (1 - 5)", class: "label-form mt-4" %>
  <%= f.number_field :priority, class: 'form-control' %>
  <%= f.submit "Create Category", class: 'btn send-button mt-4 mb-5' %>
  <% end %>
</div>

app/views/categories/show.html.erb
<div class=" col-12 bg-brown p-5">
  <h1 class="page-title-wihte"> Articles of: <%= @category.name %></h1>
</div>


<div class="container-fluid mt-5 mb-5">
  <div class="row">
    <% counter = 0 %>
    <% out = '' %>
    <% @articles.each do |article| %>
    <% counter == 2 and out == '' ? ( counter , out = 0, 'flex-row-reverse') : (counter, out = 0,  '') %>

    <div class="col-lg-6 col-md-6 col-sm-12">
      <div class="row <%= out %>">

        <div class="col-lg-6  col-md-12 category-post"  style="background:url(<%= article.image %>)">
        </div>

        <div class=" col-lg-6 col-md-12 align-self-center p-4 m-0">
          <h5 class="categories-title-category ""> <%= article.category.name %> </h5> <br>
          <h5 class="categories-title-article mt-4"> <%= article.title %> </h5>
          <p> <%= truncate(article.text, length: 125) %> </p>
          <p class="categories-rm-article ">Read More</p>
          <div class="row">
            <div class="col-8">
              <span class="categories-rm-article text-capitalize font-weight-bold" >Author: <%= article.user.name %> </span>
            </div>
            <div class="col-4 text-rigth">
              <span class="label-form">  <%= article.votes.size %> <%= vote_or_unvote(article) %></span>
            </div>
          </div>
        </div>

      </div>
    </div>
    <% counter += 1%>
    <% end %>
  </div>
</div>

app/views/home/index.html.erb
<% if @most_voted_article %>

<div class="top-post h-50" style="background:url(<%= @most_voted_article.image %>)">
  <div class="bottom-left">
    <h4 class="article-title"> <%= @most_voted_article.title %> </h4>

    <p class="article-text"> <%= truncate(@most_voted_article.text, length:100, separator: ' ') %> </p>
    <span class="vote-white">  <%= @most_voted_article.votes.size %> <%= vote_or_unvote(@most_voted_article, 'vote-white') %></span>

  </div>
</div>

<% end %>


<div class="container-fluid">


  <div class="row">

    <%  @categories.ordered_by_priority.each do |category| %>
    <% if category.articles.size > 0 %>
    <div class="col-lg-3 col-md-6 col-sm-6 p-0">
      <div class="category-post"  style="background:url(<%= category.articles.ordered_most_recent.first.image %>)">
        <h5> <%= link_to(category.name, category_path(category), :class => 'category-name m-4')%> </h5>
        <p class="article-title-category bottom-left m-4"><%= category.articles.ordered_most_recent.first.title %></p>
      </div>
    </div>
    <% end %>
    <% end %>

  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Technology Articles- Shubham Raj</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>
<%= render 'shared/navbar'  %>
<body>
  <% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
  <% end %>

  <%= yield %>
</body>
<%= render 'shared/footer'  %>
</html>

app/views/shared/_footer.html.erb
<footer class="p-2">
  <div class="container-fluid">

    <div class="row">

      <div class="col-lg-4 col-md-4">
        <%= link_to image_tag("logo-white.png", size: "120x40"), root_path, :class => 'pl-3 link-nav'%>
      </div>

      <div class="col-lg-4 col-md-4 text-center">
        <%= link_to "Privacy policy", root_path, :class => 'pl-2 link-footer'%>
        <%= link_to "Terms and condition", root_path, :class => 'pl-2 pr-2 link-footer'%>
        <span> Copyrigth 2020. All rigths reserved.</span>
      </div>

      <div class="col-lg-4 col-md-4 text-right">
        Conect with us:

          <div class="rounded-icon" >
            <%= image_tag("facebook.svg", class: 'social-icon') %>
          </div>
          <div class="rounded-icon" >
            <%= image_tag("instagram.svg", class: 'social-icon') %>
          </div>
          <div class="rounded-icon" >
            <%= image_tag("twitter.svg", class: 'social-icon') %>

        </div>
      </div>

    </div>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-light navbar-expand-md bg-faded justify-content-center sticky-top">
  <%= link_to image_tag("logo-black.png", size: "150x50"), root_path, :class => 'navbar-brand d-flex w-50 mr-auto'%>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#collapsingNavbar3">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="navbar-collapse collapse w-100" id="collapsingNavbar3">
    <ul class="navbar-nav w-100 justify-content-center">
      <li class="nav-item">
        <%= link_to "HOME", root_path, :class => 'nav-link link-nav '%>
        <% if logged_in? %>

      </li>
      <li class="nav-item">
        <%= link_to "WRITE ARTICLE", new_article_path, :class => 'nav-link link-nav '%>
        <% end %>
      </li>

    </ul>
    <ul class="nav navbar-nav ml-auto w-100 justify-content-end">
      <li class="nav-item">
        <% if logged_in? %>
        <%= link_to "LOGOUT", logout_path, :class => 'nav-link link-nav ', method: :delete %>
        <% else %>
        <%= link_to "LOGIN", login_path, :class => 'nav-link link-nav '%>
      </li>
      <li class="nav-item">

        <span class='nav-link link-nav '> | </span>

      </li>
      <li class="nav-item">

        <%= link_to "REGISTER", signup_path, :class => 'nav-link link-nav '%>
        <% end %>
      </li>
    </ul>
  </div>
</nav>

app/views/users/new.html.erb
<div class="container-fluid h-75 p-5 bg-brown">

  <div class="row h-100">
    <div class="col-md-6 my-auto">
      <div class="card m-0 p-3">
        <h1 class="page-title ">Sign Up</h1>

        <%= form_for(@user) do |f| %> <%= render 'shared/error_messages' %>
        <%= f.label :name, "Name: ", class: "label-form" %>
        <%= f.text_field :name, class: 'form-control' %>
        <%= f.submit "Create account", class: "btn send-button mt-5 mb-5" %>
        <% end %>

        <p class="label-form"> Already registed? <%= link_to "Login Now", login_path, class: 'label-form' %></p>

      </div>
    </div>
  </div>

</div>